In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s3e17/sample_submission.csv
/kaggle/input/playground-series-s3e17/train.csv
/kaggle/input/playground-series-s3e17/test.csv


In [2]:
train = pd.read_csv('/kaggle/input/playground-series-s3e17/train.csv')
test = pd.read_csv('/kaggle/input/playground-series-s3e17/test.csv')

In [3]:
train

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0            0     L50096    L                300.6                    309.6   
1            1     M20343    M                302.6                    312.1   
2            2     L49454    L                299.3                    308.5   
3            3     L53355    L                301.0                    310.9   
4            4     M24050    M                298.0                    309.0   
...        ...        ...  ...                  ...                      ...   
136424  136424     M22284    M                300.1                    311.4   
136425  136425     H38017    H                297.5                    308.5   
136426  136426     L54690    L                300.5                    311.8   
136427  136427     L53876    L                301.7                    310.9   
136428  136428     L47937    L                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  
0         0    0    0    0    0  
1         0    0    0    0    0  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
136424    0    0    0    0    0  
136425    0    0    0    0    0  
136426    0    0    0    0    0  
136427    0    0    0    0    0  
136428    0    0    0    0    0  

[136429 rows x 14 columns]

In [4]:
test

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0      136429     L50896    L                302.3                    311.5   
1      136430     L53866    L                301.7                    311.0   
2      136431     L50498    L                301.3                    310.4   
3      136432     M21232    M                300.1                    309.6   
4      136433     M19751    M                303.4                    312.3   
...       ...        ...  ...                  ...                      ...   
90949  227378     L51130    L                302.3                    311.4   
90950  227379     L47783    L                297.9                    309.8   
90951  227380     L48097    L                295.6                    306.2   
90952  227381     L48969    L                298.1                    307.8   
90953  227382     L52525    L                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  
0        0    0  
1        0    0  
2        0    0  
3        0    0  
4        0    0  
...    ...  ...  
90949    0    0  
90950    0    0  
90951    0    0  
90952    0    0  
90953    0    0  

[90954 rows x 13 columns]

In [5]:
train.columns = ['id', 'product_id', 'type', 'air_temperature', 'process_temperature', 'rotational_speed', 'torque', 'tool_wear', 'machine_failure', 'twf', 'hdf', 'pwf', 'osf', 'rnf']
test.columns = ['id', 'product_id', 'type', 'air_temperature', 'process_temperature', 'rotational_speed', 'torque', 'tool_wear', 'twf', 'hdf', 'pwf', 'osf', 'rnf']

In [6]:
train

id product_id type  air_temperature  process_temperature  \
0            0     L50096    L            300.6                309.6   
1            1     M20343    M            302.6                312.1   
2            2     L49454    L            299.3                308.5   
3            3     L53355    L            301.0                310.9   
4            4     M24050    M            298.0                309.0   
...        ...        ...  ...              ...                  ...   
136424  136424     M22284    M            300.1                311.4   
136425  136425     H38017    H            297.5                308.5   
136426  136426     L54690    L            300.5                311.8   
136427  136427     L53876    L            301.7                310.9   
136428  136428     L47937    L            296.9                308.1   

        rotational_speed  torque  tool_wear  machine_failure  twf  hdf  pwf  \
0                   1596    36.1        140                0    0    0    0   
1                   1759    29.1        200                0    0    0    0   
2                   1805    26.5         25                0    0    0    0   
3                   1524    44.3        197                0    0    0    0   
4                   1641    35.4         34                0    0    0    0   
...                  ...     ...        ...              ...  ...  ...  ...   
136424              1530    37.5        210                0    0    0    0   
136425              1447    49.1          2                0    0    0    0   
136426              1524    38.5        214                0    0    0    0   
136427              1447    46.3         42                0    0    0    0   
136428              1557    39.3        229                0    0    0    0   

        osf  rnf  
0         0    0  
1         0    0  
2         0    0  
3         0    0  
4         0    0  
...     ...  ...  
136424    0    0  
136425    0    0  
136426    0    0  
136427    0    0  
136428    0    0  

[136429 rows x 14 columns]

In [7]:
test

id product_id type  air_temperature  process_temperature  \
0      136429     L50896    L            302.3                311.5   
1      136430     L53866    L            301.7                311.0   
2      136431     L50498    L            301.3                310.4   
3      136432     M21232    M            300.1                309.6   
4      136433     M19751    M            303.4                312.3   
...       ...        ...  ...              ...                  ...   
90949  227378     L51130    L            302.3                311.4   
90950  227379     L47783    L            297.9                309.8   
90951  227380     L48097    L            295.6                306.2   
90952  227381     L48969    L            298.1                307.8   
90953  227382     L52525    L            303.5                312.8   

       rotational_speed  torque  tool_wear  twf  hdf  pwf  osf  rnf  
0                  1499    38.0         60    0    0    0    0    0  
1                  1713    28.8         17    0    0    0    0    0  
2                  1525    37.7         96    0    0    0    0    0  
3                  1479    47.6          5    0    0    0    0    0  
4                  1515    41.3        114    0    0    0    0    0  
...                 ...     ...        ...  ...  ...  ...  ...  ...  
90949              1484    40.4         15    0    0    0    0    0  
90950              1542    33.8         31    0    0    0    0    0  
90951              1501    41.4        187    0    0    0    0    0  
90952              1534    40.3         69    0    0    0    0    0  
90953              1534    36.1         92    0    0    0    0    0  

[90954 rows x 13 columns]

In [8]:
train['product_id'].unique()

array(['L50096', 'M20343', 'L49454', ..., 'M18739', 'L50940', 'L48036'],
      dtype=object)

In [9]:
del train['product_id']
del test['product_id']

In [10]:
train['type'].unique()

array(['L', 'M', 'H'], dtype=object)

In [11]:
test['type'].unique()

array(['L', 'M', 'H'], dtype=object)

In [12]:
train = pd.get_dummies(train, columns = ['type'])
test = pd.get_dummies(test, columns = ['type'])

In [13]:
train

id  air_temperature  process_temperature  rotational_speed  \
0            0            300.6                309.6              1596   
1            1            302.6                312.1              1759   
2            2            299.3                308.5              1805   
3            3            301.0                310.9              1524   
4            4            298.0                309.0              1641   
...        ...              ...                  ...               ...   
136424  136424            300.1                311.4              1530   
136425  136425            297.5                308.5              1447   
136426  136426            300.5                311.8              1524   
136427  136427            301.7                310.9              1447   
136428  136428            296.9                308.1              1557   

        torque  tool_wear  machine_failure  twf  hdf  pwf  osf  rnf  type_H  \
0         36.1        140                0    0    0    0    0    0       0   
1         29.1        200                0    0    0    0    0    0       0   
2         26.5         25                0    0    0    0    0    0       0   
3         44.3        197                0    0    0    0    0    0       0   
4         35.4         34                0    0    0    0    0    0       0   
...        ...        ...              ...  ...  ...  ...  ...  ...     ...   
136424    37.5        210                0    0    0    0    0    0       0   
136425    49.1          2                0    0    0    0    0    0       1   
136426    38.5        214                0    0    0    0    0    0       0   
136427    46.3         42                0    0    0    0    0    0       0   
136428    39.3        229                0    0    0    0    0    0       0   

        type_L  type_M  
0            1       0  
1            0       1  
2            1       0  
3            1       0  
4            0       1  
...        ...     ...  
136424       0       1  
136425       0       0  
136426       1       0  
136427       1       0  
136428       1       0  

[136429 rows x 15 columns]

In [14]:
test

id  air_temperature  process_temperature  rotational_speed  torque  \
0      136429            302.3                311.5              1499    38.0   
1      136430            301.7                311.0              1713    28.8   
2      136431            301.3                310.4              1525    37.7   
3      136432            300.1                309.6              1479    47.6   
4      136433            303.4                312.3              1515    41.3   
...       ...              ...                  ...               ...     ...   
90949  227378            302.3                311.4              1484    40.4   
90950  227379            297.9                309.8              1542    33.8   
90951  227380            295.6                306.2              1501    41.4   
90952  227381            298.1                307.8              1534    40.3   
90953  227382            303.5                312.8              1534    36.1   

       tool_wear  twf  hdf  pwf  osf  rnf  type_H  type_L  type_M  
0             60    0    0    0    0    0       0       1       0  
1             17    0    0    0    0    0       0       1       0  
2             96    0    0    0    0    0       0       1       0  
3              5    0    0    0    0    0       0       0       1  
4            114    0    0    0    0    0       0       0       1  
...          ...  ...  ...  ...  ...  ...     ...     ...     ...  
90949         15    0    0    0    0    0       0       1       0  
90950         31    0    0    0    0    0       0       1       0  
90951        187    0    0    0    0    0       0       1       0  
90952         69    0    0    0    0    0       0       1       0  
90953         92    0    0    0    0    0       0       1       0  

[90954 rows x 14 columns]

In [15]:
train['twf'].unique()

array([0, 1])

In [16]:
train['hdf'].unique()

array([0, 1])

In [17]:
train['pwf'].unique()

array([0, 1])

In [18]:
train['osf'].unique()

array([0, 1])

In [19]:
train['rnf'].unique()

array([0, 1])

In [20]:
train.isnull().value_counts()

id     air_temperature  process_temperature  rotational_speed  torque  tool_wear  machine_failure  twf    hdf    pwf    osf    rnf    type_H  type_L  type_M
False  False            False                False             False   False      False            False  False  False  False  False  False   False   False     136429
dtype: int64

In [21]:
train.dtypes

id                       int64
air_temperature        float64
process_temperature    float64
rotational_speed         int64
torque                 float64
tool_wear                int64
machine_failure          int64
twf                      int64
hdf                      int64
pwf                      int64
osf                      int64
rnf                      int64
type_H                   uint8
type_L                   uint8
type_M                   uint8
dtype: object

In [22]:
test.dtypes

id                       int64
air_temperature        float64
process_temperature    float64
rotational_speed         int64
torque                 float64
tool_wear                int64
twf                      int64
hdf                      int64
pwf                      int64
osf                      int64
rnf                      int64
type_H                   uint8
type_L                   uint8
type_M                   uint8
dtype: object

In [23]:
from sklearn.model_selection import train_test_split

y = train['machine_failure']
del train['machine_failure']
X = train

train_X, val_X, train_y, val_y = train_test_split(X, y)

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score

dtc_model = DecisionTreeClassifier()
dtc_model.fit(train_X, train_y)
dtc_pred = dtc_model.predict(val_X)

dtc_ras = roc_auc_score(val_y, dtc_pred)

In [25]:
from sklearn.ensemble import RandomForestClassifier

rfc_model = RandomForestClassifier()
rfc_model.fit(train_X, train_y)
rfc_pred = rfc_model.predict(val_X)

rfc_ras = roc_auc_score(val_y, rfc_pred)

In [ ]:
from CatBoost import CatBoost